CREATE TABLE IF NOT EXISTS project (
    id INTEGER PRIMARY KEY AUTOINCREMENT
) STRICT;
CREATE TABLE IF NOT EXISTS location (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    project_id INTEGER NOT NULL,
    image BLOB NOT NULL,
    -- scale is in terms of pixels per metre
    scale REAL NOT NULL,
    FOREIGN KEY(project_id) REFERENCES project(id) ON DELETE CASCADE
) STRICT;
CREATE TABLE IF NOT EXISTS chains (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    location_id INTEGER NOT NULL,
    points TEXT NOT NULL,
    FOREIGN KEY(location_id) REFERENCES location(id) ON DELETE CASCADE
) STRICT;
CREATE TABLE IF NOT EXISTS cattails (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    location_id INTEGER NOT NULL,
    x REAL NOT NULL,
    y REAL NOT NULL,
    FOREIGN KEY(location_id) REFERENCES location(id) ON DELETE CASCADE
) STRICT;