[project]
name = "touch-grass-2d"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "imgui-bundle>=1.92.4",
    "pillow>=11.3.0",
    "pyopengl>=3.1.10",
]

[dependency-groups]
dev = [
    "jurigged>=0.6.1",
]
